---
name: "Bump tag name"
description: "Automaticly generate the version tag"
inputs:
  token:
    description: "Your GITHUB_TOKEN"
    default: ${{ github.token }}
    required: false

outputs:
  tag:
    description: "Version Tag"

runs:
  using: "node16"
  main: "action/index.js"
